data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'airflow-######'  # Add your Project ID here.
    dataset: retail
soda_cloud:
host: cloud.soda.io
api_key_id: ec1bd081-1cfc-4037-93cc-d2ba###### # Add your API key here.
api_key_secret: CcCCtCBhMIdju4VLKovy6Tha8by7sm7AD4############ # Add your API Key secret here. 